### ISSUE TITLE
Icon not showing up

### ISSUE THREAD

**Issue by nyurik** [asvanberg/blueprint-request#1]
Hi, I would love to use your mod, but the button doesn't show up for some reason. I currently have Helmod planner and FNEI installed (the two buttons that I do see), plus LTN and a few more mods.  Are there steps I can use to debug the issue? Thx!
P.S. Running on 1.1.36

**Comment by asvanberg** [comment]
Do you have a blueprint in the cursor? The button is only there if you do.
